name: flowery_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  flutter_bloc: ^9.1.0
  flutter_svg: ^2.1.0
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4
  iconsax_flutter: ^1.0.0
  another_flushbar: ^1.12.30
  connectivity_plus: ^6.1.4
  injectable: ^2.5.0
  get_it: ^7.6.7
  flutter_native_splash: ^2.4.6
  lottie: ^3.3.1
  retrofit: ^4.4.1
  logger: ^2.4.0
  json_annotation: ^4.9.0
  pretty_dio_logger: ^1.4.0
  pin_code_fields: ^8.0.1
  mockito: ^5.4.5
  bloc_test: ^10.0.0
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  equatable: ^2.0.7

dev_dependencies:
  build_runner: ^2.4.6
  injectable_generator: ^2.5.0
  retrofit_generator: ^9.1.5
  json_serializable: ^6.7.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# شيل الـ overrides إلا لو عندك سبب قوي
# dependency_overrides:
#   analyzer: ^6.2.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/animations/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter_18pt-Thin.ttf
          weight: 100
        - asset: assets/fonts/inter/Inter_18pt-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/inter/Inter_18pt-Light.ttf
          weight: 300
        - asset: assets/fonts/inter/Inter_18pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/inter/Inter_18pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/inter/Inter_18pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/inter/Inter_18pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/inter/Inter_18pt-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/inter/Inter_18pt-Black.ttf
          weight: 900
