// Mocks generated by Mockito 5.4.6 from annotations
// in flowery_app/test/api/data_source/register/remote_data_source/register_remote_data_source_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i12;

import 'package:connectivity_plus/connectivity_plus.dart' as _i18;
import 'package:connectivity_plus_platform_interface/connectivity_plus_platform_interface.dart'
    as _i19;
import 'package:flowery_app/api/client/api_client.dart' as _i11;
import 'package:flowery_app/api/requests/forget_password_request/forget_password_request.dart'
    as _i15;
import 'package:flowery_app/api/requests/login_request/login_request_model.dart'
    as _i13;
import 'package:flowery_app/api/requests/profile_reset_password/profile_reset_password_request.dart'
    as _i16;
import 'package:flowery_app/api/requests/register_request/register_request.dart'
    as _i14;
import 'package:flowery_app/api/responses/categories_response/categories_response.dart'
    as _i5;
import 'package:flowery_app/api/responses/forget_password_response/forget_password_response.dart'
    as _i7;
import 'package:flowery_app/api/responses/home_products/products_response_model.dart'
    as _i2;
import 'package:flowery_app/api/responses/login_response/login_response.dart'
    as _i3;
import 'package:flowery_app/api/responses/products_response/products_response.dart'
    as _i6;
import 'package:flowery_app/api/responses/profile_reset_password/profile_reset_password_response.dart'
    as _i9;
import 'package:flowery_app/api/responses/profile_response/profile_response.dart'
    as _i8;
import 'package:flowery_app/api/responses/register_response/register_response.dart'
    as _i4;
import 'package:flowery_app/core/secure_storage/secure_storage.dart' as _i17;
import 'package:flutter_secure_storage/flutter_secure_storage.dart' as _i10;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeProductsResponseModel_0 extends _i1.SmartFake
    implements _i2.ProductsResponseModel {
  _FakeProductsResponseModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLoginResponse_1 extends _i1.SmartFake implements _i3.LoginResponse {
  _FakeLoginResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRegisterResponse_2 extends _i1.SmartFake
    implements _i4.RegisterResponse {
  _FakeRegisterResponse_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCategoriesResponse_3 extends _i1.SmartFake
    implements _i5.CategoriesResponse {
  _FakeCategoriesResponse_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProductsResponse_4 extends _i1.SmartFake
    implements _i6.ProductsResponse {
  _FakeProductsResponse_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeForgetPasswordResponseModel_5 extends _i1.SmartFake
    implements _i7.ForgetPasswordResponseModel {
  _FakeForgetPasswordResponseModel_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProfileResponse_6 extends _i1.SmartFake
    implements _i8.ProfileResponse {
  _FakeProfileResponse_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProfileResetPasswordResponse_7 extends _i1.SmartFake
    implements _i9.ProfileResetPasswordResponse {
  _FakeProfileResetPasswordResponse_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeFlutterSecureStorage_8 extends _i1.SmartFake
    implements _i10.FlutterSecureStorage {
  _FakeFlutterSecureStorage_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i11.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.Future<_i2.ProductsResponseModel> getHomeData({
    required String? token,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getHomeData, [], {#token: token}),
            returnValue: _i12.Future<_i2.ProductsResponseModel>.value(
              _FakeProductsResponseModel_0(
                this,
                Invocation.method(#getHomeData, [], {#token: token}),
              ),
            ),
          )
          as _i12.Future<_i2.ProductsResponseModel>);

  @override
  _i12.Future<_i3.LoginResponse> login({
    required _i13.LoginRequestModel? request,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {#request: request}),
            returnValue: _i12.Future<_i3.LoginResponse>.value(
              _FakeLoginResponse_1(
                this,
                Invocation.method(#login, [], {#request: request}),
              ),
            ),
          )
          as _i12.Future<_i3.LoginResponse>);

  @override
  _i12.Future<_i4.RegisterResponse> register({
    required _i14.RegisterRequest? request,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#register, [], {#request: request}),
            returnValue: _i12.Future<_i4.RegisterResponse>.value(
              _FakeRegisterResponse_2(
                this,
                Invocation.method(#register, [], {#request: request}),
              ),
            ),
          )
          as _i12.Future<_i4.RegisterResponse>);

  @override
  _i12.Future<_i5.CategoriesResponse> fetchAllCategories() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllCategories, []),
            returnValue: _i12.Future<_i5.CategoriesResponse>.value(
              _FakeCategoriesResponse_3(
                this,
                Invocation.method(#fetchAllCategories, []),
              ),
            ),
          )
          as _i12.Future<_i5.CategoriesResponse>);

  @override
  _i12.Future<_i6.ProductsResponse> fetchAllProducts() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllProducts, []),
            returnValue: _i12.Future<_i6.ProductsResponse>.value(
              _FakeProductsResponse_4(
                this,
                Invocation.method(#fetchAllProducts, []),
              ),
            ),
          )
          as _i12.Future<_i6.ProductsResponse>);

  @override
  _i12.Future<_i7.ForgetPasswordResponseModel> forgetPassword({
    required _i15.ForgetPasswordRequestDto? request,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#forgetPassword, [], {#request: request}),
            returnValue: _i12.Future<_i7.ForgetPasswordResponseModel>.value(
              _FakeForgetPasswordResponseModel_5(
                this,
                Invocation.method(#forgetPassword, [], {#request: request}),
              ),
            ),
          )
          as _i12.Future<_i7.ForgetPasswordResponseModel>);

  @override
  _i12.Future<_i8.ProfileResponse> getUserData({required String? token}) =>
      (super.noSuchMethod(
            Invocation.method(#getUserData, [], {#token: token}),
            returnValue: _i12.Future<_i8.ProfileResponse>.value(
              _FakeProfileResponse_6(
                this,
                Invocation.method(#getUserData, [], {#token: token}),
              ),
            ),
          )
          as _i12.Future<_i8.ProfileResponse>);

  @override
  _i12.Future<void> logout({required String? token}) =>
      (super.noSuchMethod(
            Invocation.method(#logout, [], {#token: token}),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<_i9.ProfileResetPasswordResponse> profileResetPassword({
    required String? token,
    required _i16.ProfileResetPasswordRequest? entity,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#profileResetPassword, [], {
              #token: token,
              #entity: entity,
            }),
            returnValue: _i12.Future<_i9.ProfileResetPasswordResponse>.value(
              _FakeProfileResetPasswordResponse_7(
                this,
                Invocation.method(#profileResetPassword, [], {
                  #token: token,
                  #entity: entity,
                }),
              ),
            ),
          )
          as _i12.Future<_i9.ProfileResetPasswordResponse>);
}

/// A class which mocks [SecureStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockSecureStorage extends _i1.Mock implements _i17.SecureStorage {
  MockSecureStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.FlutterSecureStorage get storage =>
      (super.noSuchMethod(
            Invocation.getter(#storage),
            returnValue: _FakeFlutterSecureStorage_8(
              this,
              Invocation.getter(#storage),
            ),
          )
          as _i10.FlutterSecureStorage);

  @override
  _i12.Future<void> saveData({required String? key, required String? value}) =>
      (super.noSuchMethod(
            Invocation.method(#saveData, [], {#key: key, #value: value}),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> saveUserToken({required String? token}) =>
      (super.noSuchMethod(
            Invocation.method(#saveUserToken, [], {#token: token}),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<String?> getData({required String? key}) =>
      (super.noSuchMethod(
            Invocation.method(#getData, [], {#key: key}),
            returnValue: _i12.Future<String?>.value(),
          )
          as _i12.Future<String?>);

  @override
  _i12.Future<void> deleteData({required String? key}) =>
      (super.noSuchMethod(
            Invocation.method(#deleteData, [], {#key: key}),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);
}

/// A class which mocks [Connectivity].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectivity extends _i1.Mock implements _i18.Connectivity {
  MockConnectivity() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.Stream<List<_i19.ConnectivityResult>> get onConnectivityChanged =>
      (super.noSuchMethod(
            Invocation.getter(#onConnectivityChanged),
            returnValue: _i12.Stream<List<_i19.ConnectivityResult>>.empty(),
          )
          as _i12.Stream<List<_i19.ConnectivityResult>>);

  @override
  _i12.Future<List<_i19.ConnectivityResult>> checkConnectivity() =>
      (super.noSuchMethod(
            Invocation.method(#checkConnectivity, []),
            returnValue: _i12.Future<List<_i19.ConnectivityResult>>.value(
              <_i19.ConnectivityResult>[],
            ),
          )
          as _i12.Future<List<_i19.ConnectivityResult>>);
}
