name: "Validate Branch Name"

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  validate-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate branch name
        shell: bash
        run: |
          branch="${GITHUB_REF##*/}"
          echo "Branch is: $branch"
          echo "$branch" | grep -Eq "^(feature|fix|release|hotfix|build|test)/(FAT1-[0-9]+|[A-Z]+-[0-9]+)(-[A-Za-z0-9]+)*$"
          if [ $? -ne 0 ]; then
            echo "❌ Branch name does not follow the required convention!"
            exit 1
          else
            echo "✅ Branch name is valid."
          fi
