name: "Validate Branch Name"

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  validate-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate branch name
        run: |
           if [ -n "$GITHUB_HEAD_REF" ]; then
            BRANCH_NAME="$GITHUB_HEAD_REF"
          else
            BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          fi

          echo "Current branch: $BRANCH_NAME"

           if [[ ! "$BRANCH_NAME" =~ ^(feature|bugfix|hotfix|release)\/[A-Za-z0-9]+-[0-9]+-[a-z0-9-]+$ ]]; then
            echo "❌ Branch name '$BRANCH_NAME' is invalid!"
            echo "✅ Use format: feature/ABC-123-description"
            exit 1
          fi

          echo "✅ Branch name '$BRANCH_NAME' is valid."
