 name: "Validate Branch Name"

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  validate-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate branch name
        id: branch
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "branch=${{ github.head_ref }}" >> $GITHUB_OUTPUT
          else
            echo "branch=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          fi

      - name: Validate branch name
        run: |
          BRANCH="${{ steps.branch.outputs.branch }}"
          echo "Current branch: $BRANCH"

          if [[ ! "$BRANCH" =~ ^(feature|bugfix|hotfix|release)\/[A-Za-z0-9]+-[0-9]+-[a-z0-9-]+$ ]]; then
            echo "❌ Branch name '$BRANCH' is invalid!"
            echo "✅ Use format: feature/ABC-123-description"
            exit 1
          fi

          echo "✅ Branch name '$BRANCH' is valid."
